# Generated by Django 4.0.3 on 2022-04-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(default='C', max_length=2),
        ),
    ]
