# Generated by Django 4.0.3 on 2022-04-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobs_arquivo_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='arquivo_final',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
